apiVersion: cilium.io/v2	
kind: CiliumIdentity	
metadata:	
  generation: 1	
  labels:	
    app.kubernetes.io/instance: nginx	
    io.cilium.k8s.policy.cluster: default	
    io.cilium.k8s.policy.serviceaccount: default	
    io.kubernetes.pod.namespace: default	
    run: nginx	
  managedFields:	
    - apiVersion: cilium.io/v2	
      fieldsType: FieldsV1	
      fieldsV1:	
        'f:metadata':	
          'f:labels':	
            .: {}	
            'f:app.kubernetes.io/instance': {}	
            'f:io.cilium.k8s.policy.cluster': {}	
            'f:io.cilium.k8s.policy.serviceaccount': {}	
            'f:io.kubernetes.pod.namespace': {}	
            'f:run': {}	
        'f:security-labels':	
          .: {}	
          'f:k8s:app.kubernetes.io/instance': {}	
          'f:k8s:io.cilium.k8s.namespace.labels.kubernetes.io/metadata.name': {}	
          'f:k8s:io.cilium.k8s.policy.cluster': {}	
          'f:k8s:io.cilium.k8s.policy.serviceaccount': {}	
          'f:k8s:io.kubernetes.pod.namespace': {}	
          'f:k8s:run': {}	
      manager: cilium-agent	
      operation: Update	
      time: '2023-04-26T08:13:31Z'	
  name: '7784'	
  resourceVersion: '487092'	
  uid: 500f0a62-fafc-4658-a64e-073958b3b7ae	
security-labels:	
  'k8s:app.kubernetes.io/instance': nginx	
  'k8s:io.cilium.k8s.namespace.labels.kubernetes.io/metadata.name': default	
  'k8s:io.cilium.k8s.policy.cluster': default	
  'k8s:io.cilium.k8s.policy.serviceaccount': default	
  'k8s:io.kubernetes.pod.namespace': default	
  'k8s:run': nginx
